# Generated by Django 6.0.5 on 2026-05-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='科目名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_system', models.BooleanField(default=False, help_text='系统内置科目不可删除', verbose_name='系统内置')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '费用科目',
                'verbose_name_plural': '费用科目',
                'db_table': 'project_cost_category',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='合作商名称')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '合作商',
                'verbose_name_plural': '合作商',
                'db_table': 'project_partner',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('project_type', models.CharField(choices=[('first_test', '首次血检'), ('course_mgmt', '疗程管理')], max_length=20, verbose_name='项目类型')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='首次血检:检测费单价; 疗程管理:疗程总价', max_digits=12, verbose_name='单价')),
                ('duration_months', models.IntegerField(default=1, help_text='仅疗程管理有效，首次血检固定为1', verbose_name='疗程时长(月)')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.partner', verbose_name='合作商')),
            ],
            options={
                'verbose_name': '合作项目',
                'verbose_name_plural': '合作项目',
                'db_table': 'project_project',
                'ordering': ['partner', 'order'],
                'unique_together': {('partner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ManualCostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('cost_date', models.DateField(verbose_name='发生日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_costs', to='projects.costcategory', verbose_name='费用科目')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_costs', to='projects.project', verbose_name='归属项目')),
            ],
            options={
                'verbose_name': '手工费用',
                'verbose_name_plural': '手工费用',
                'db_table': 'project_manual_cost',
                'ordering': ['-cost_date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueShareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_ratio', models.DecimalField(decimal_places=4, default=0.5, help_text='如0.50表示合作方分50%', max_digits=5, verbose_name='分成比例')),
                ('deduction_rate', models.DecimalField(decimal_places=4, default=0.1, help_text='如0.10表示先扣除10%服务费', max_digits=5, verbose_name='服务费扣除比例')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_config', to='projects.partner', verbose_name='合作商')),
            ],
            options={
                'verbose_name': '分成配置',
                'verbose_name_plural': '分成配置',
                'db_table': 'project_share_config',
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('payment_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='前台收款收入')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='收入合计')),
                ('cost_details', models.JSONField(blank=True, default=dict, help_text='{"血检": 5000, "打针": 1200, "补剂": 800, ...}', verbose_name='费用明细')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='费用合计')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='毛利')),
                ('share_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='应付分成')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='计算时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '月度报表',
                'verbose_name_plural': '月度报表',
                'db_table': 'project_monthly_report',
                'ordering': ['-year', '-month', 'project'],
                'unique_together': {('project', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ProjectCategoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_configs', to='projects.costcategory', verbose_name='科目')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_configs', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目科目配置',
                'verbose_name_plural': '项目科目配置',
                'db_table': 'project_category_config',
                'unique_together': {('project', 'category')},
            },
        ),
    ]
