# Generated by Django 6.0.5 on 2026-05-24 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='deductible_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='仅计入配置中勾选的科目', max_digits=15, verbose_name='可扣除费用合计'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='收入 × 服务费扣除比例', max_digits=15, verbose_name='服务费扣除'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='share_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='收入 - 服务费 - 可扣除费用', max_digits=15, verbose_name='分成基数'),
        ),
        migrations.AddField(
            model_name='revenueshareconfig',
            name='deductible_categories',
            field=models.ManyToManyField(blank=True, help_text='勾选哪些科目在分成前扣除', related_name='share_configs', to='projects.costcategory', verbose_name='可扣除费用科目'),
        ),
        migrations.AlterField(
            model_name='revenueshareconfig',
            name='deduction_rate',
            field=models.DecimalField(decimal_places=4, default=0.1, help_text='如0.10表示先从收入扣10%服务费', max_digits=5, verbose_name='服务费扣除比例'),
        ),
        migrations.CreateModel(
            name='RevenueShareConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_ratio', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='分成比例')),
                ('deduction_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='服务费扣除比例')),
                ('deductible_keys', models.JSONField(default=list, verbose_name='可扣除科目')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_history', to='projects.partner', verbose_name='合作商')),
            ],
            options={
                'verbose_name': '配置历史',
                'verbose_name_plural': '配置历史',
                'db_table': 'project_share_config_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
