# Generated by Django 6.0.5 on 2026-05-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_share_v4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenueshareconfig',
            options={'verbose_name': '项目分成配置', 'verbose_name_plural': '项目分成配置'},
        ),
        migrations.AddField(
            model_name='project',
            name='short_name',
            field=models.CharField(blank=True, help_text='如"抗衰老首次血检"，用于Excel列匹配', max_length=50, verbose_name='项目简称'),
        ),
        migrations.AlterField(
            model_name='revenueshareconfig',
            name='deductible_categories',
            field=models.ManyToManyField(blank=True, help_text='勾选哪些科目在分成前扣除（护士服务费不扣实际成本，而是 收入×比例）', related_name='share_configs', to='projects.costcategory', verbose_name='可扣除费用科目'),
        ),
    ]
