# Generated by Django 6.0.5 on 2026-05-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, max_length=100, verbose_name='客户姓名')),
                ('bill_date', models.DateField(db_index=True, verbose_name='日期')),
                ('item_name', models.CharField(max_length=255, verbose_name='名称')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('hkd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='港币金额')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='来源文件')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
            ],
            options={
                'verbose_name': '导入账单明细',
                'verbose_name_plural': '导入账单明细',
                'db_table': 'billing_import',
                'ordering': ['-bill_date'],
            },
        ),
        migrations.CreateModel(
            name='BillTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板说明')),
                ('partner_type', models.CharField(blank=True, max_length=50, verbose_name='适用合作方')),
                ('fields_config', models.JSONField(default=list, help_text='JSON array of field definitions', verbose_name='字段配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '账单模板',
                'verbose_name_plural': '账单模板',
                'db_table': 'billing_template',
            },
        ),
        migrations.CreateModel(
            name='GeneratedBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100, verbose_name='合作方')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('bill_data', models.JSONField(default=dict, verbose_name='账单数据')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总金额')),
                ('hkd_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='港币总金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('generated', '已生成'), ('sent', '已发送')], default='draft', max_length=20, verbose_name='状态')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billtemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '已生成账单',
                'verbose_name_plural': '已生成账单',
                'db_table': 'billing_generated',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
