# Generated by Django 6.0.5 on 2026-05-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='字段名称')),
                ('field_type', models.CharField(choices=[('text', '文本'), ('number', '数字'), ('date', '日期'), ('boolean', '是/否'), ('select', '下拉选择')], default='text', max_length=20, verbose_name='字段类型')),
                ('entity_type', models.CharField(db_index=True, help_text='如: customer, lab_bill, expense 等', max_length=100, verbose_name='关联实体')),
                ('options', models.TextField(blank=True, help_text='仅下拉类型使用，每行一个选项', verbose_name='下拉选项')),
                ('is_required', models.BooleanField(default=False, verbose_name='必填')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '自定义字段定义',
                'verbose_name_plural': '自定义字段定义',
                'db_table': 'core_custom_field_def',
                'ordering': ['entity_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(blank=True, verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('config_type', models.CharField(choices=[('text', '文本'), ('number', '数字'), ('json', 'JSON'), ('boolean', '布尔')], default='text', max_length=20, verbose_name='类型')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='分类')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'core_system_config',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.PositiveIntegerField(verbose_name='实体ID')),
                ('value_text', models.TextField(blank=True, default='', verbose_name='文本值')),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='数字值')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='日期值')),
                ('value_boolean', models.BooleanField(default=False, verbose_name='布尔值')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='实体类型')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.customfielddefinition', verbose_name='字段定义')),
            ],
            options={
                'verbose_name': '自定义字段值',
                'verbose_name_plural': '自定义字段值',
                'db_table': 'core_custom_field_val',
                'indexes': [models.Index(fields=['content_type', 'entity_id'], name='core_custom_content_f362e2_idx')],
                'unique_together': {('definition', 'content_type', 'entity_id')},
            },
        ),
    ]
