# Generated by Django 6.0.5 on 2026-05-11 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='实验室名称')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='简称')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '合作实验室',
                'verbose_name_plural': '合作实验室',
                'db_table': 'lab_bills_partner',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabBillImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('records_imported', models.IntegerField(default=0, verbose_name='导入记录数')),
                ('records_skipped', models.IntegerField(default=0, verbose_name='跳过记录数')),
                ('errors', models.TextField(blank=True, verbose_name='错误信息')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('lab_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_bills.labpartner', verbose_name='合作方')),
            ],
            options={
                'verbose_name': '导入日志',
                'verbose_name_plural': '导入日志',
                'db_table': 'lab_bills_import_log',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='LabBillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer_name', models.CharField(db_index=True, max_length=100, verbose_name='客户姓名')),
                ('test_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='检测日期')),
                ('test_package', models.CharField(blank=True, max_length=255, verbose_name='检测项目/套餐')),
                ('package_code', models.CharField(blank=True, max_length=100, verbose_name='套餐编码')),
                ('test_quantity', models.IntegerField(default=1, verbose_name='检测数量')),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='标准单价')),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='如 0.8 表示8折', max_digits=5, verbose_name='折扣')),
                ('settlement_price', models.DecimalField(decimal_places=2, default=0, help_text='折后价格，直接取自实验室账单', max_digits=12, verbose_name='实际结算价(折后)')),
                ('payer', models.CharField(blank=True, choices=[('personal', '个人'), ('taikang', '泰康'), ('msh', 'MSH'), ('pingan', '平安'), ('hongkong', '香港'), ('union', '平台工会')], db_index=True, max_length=20, verbose_name='付款人')),
                ('department', models.CharField(blank=True, choices=[('health_mgmt', '健康管理'), ('daily_med', '日常医疗')], db_index=True, max_length=20, verbose_name='科室')),
                ('project', models.CharField(blank=True, choices=[('anti_aging', '抗衰老'), ('anti_aging_first', '抗衰老首次血检'), ('lifestyle', '生活方式门诊'), ('lifestyle_first', '生活方式门诊首次血检'), ('hormone', '荷尔蒙'), ('hormone_first', '荷尔蒙首次血检'), ('gut_flora', '肠道菌群'), ('alzheimers', '阿尔兹海默症'), ('glucose', '血糖代谢检测'), ('routine', '其他常规门诊')], db_index=True, max_length=30, verbose_name='项目')),
                ('custom_field_1', models.CharField(blank=True, max_length=255, verbose_name='自定义字段1')),
                ('custom_field_2', models.CharField(blank=True, max_length=255, verbose_name='自定义字段2')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='录入时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('lab_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_records', to='lab_bills.labpartner', verbose_name='合作方')),
            ],
            options={
                'verbose_name': '实验室账单记录',
                'verbose_name_plural': '实验室账单记录',
                'db_table': 'lab_bills_record',
                'ordering': ['-test_date', '-created_at'],
                'indexes': [models.Index(fields=['lab_partner', 'test_date'], name='lab_bills_r_lab_par_408e94_idx'), models.Index(fields=['customer_name'], name='lab_bills_r_custome_099f7e_idx'), models.Index(fields=['payer', 'project'], name='lab_bills_r_payer_b97d86_idx')],
            },
        ),
    ]
