# Generated by Django 6.0.5 on 2026-05-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_bills', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='labbillrecord',
            new_name='lab_bills_r_payer_84cb9b_idx',
            old_name='lab_bills_r_payer_b97d86_idx',
        ),
        migrations.AddField(
            model_name='labbillrecord',
            name='project_tag',
            field=models.CharField(blank=True, choices=[('anti_aging', '抗衰老'), ('anti_aging_first', '抗衰老首次血检'), ('lifestyle', '生活方式门诊'), ('lifestyle_first', '生活方式门诊首次血检'), ('hormone', '荷尔蒙'), ('hormone_first', '荷尔蒙首次血检'), ('gut_flora', '肠道菌群'), ('alzheimers', '阿尔兹海默症'), ('glucose', '血糖代谢检测'), ('routine', '其他常规门诊')], db_index=True, max_length=30, verbose_name='项目标签(旧)'),
        ),
        migrations.AlterField(
            model_name='labbillrecord',
            name='project',
            field=models.ForeignKey(blank=True, help_text='必选：6个合作项目之一（华测/迪恩等实验室血检账单计入该项目的血检费用）', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_bill_records', to='projects.project', verbose_name='归属项目'),
        ),
    ]
