# Generated by Django 6.0.5 on 2026-05-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='日期')),
                ('type', models.CharField(choices=[('income', '收款'), ('expense', '支出'), ('reimburse', '报销')], max_length=20, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('description', models.CharField(max_length=255, verbose_name='说明')),
                ('payee', models.CharField(blank=True, max_length=100, verbose_name='收款/付款人')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='费用类别')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '现金记录',
                'verbose_name_plural': '现金记录',
                'db_table': 'frontdesk_cash',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, max_length=100, verbose_name='客户姓名')),
                ('payment_date', models.DateField(db_index=True, verbose_name='收款日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('project', models.CharField(max_length=200, verbose_name='收费项目')),
                ('payment_type', models.CharField(choices=[('outpatient', '门诊'), ('lab', '检测'), ('medication', '药费'), ('injection', '打针/输液'), ('supplements', '保健品'), ('other', '其他')], default='outpatient', max_length=20, verbose_name='收费类型')),
                ('payer_type', models.CharField(choices=[('self', '自费'), ('pingan', '平安保险'), ('msh', 'MSH保险'), ('taikang', '泰康保险'), ('corporate', '企业合作')], default='self', help_text='付款方类型：自费/保险/企业', max_length=20, verbose_name='收入类型')),
                ('transaction_ref', models.CharField(blank=True, help_text='通联支付流水号', max_length=100, verbose_name='交易流水号')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='来源文件')),
                ('insurance_claimed', models.BooleanField(default=False, verbose_name='已申请理赔')),
                ('insurance_claim_date', models.DateField(blank=True, null=True, verbose_name='理赔日期')),
                ('insurance_status', models.CharField(blank=True, max_length=20, verbose_name='理赔状态')),
                ('invoiced', models.BooleanField(default=False, verbose_name='已开票')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='发票号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '收款记录',
                'verbose_name_plural': '收款记录',
                'db_table': 'frontdesk_payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
