# Generated by Django 6.0.5 on 2026-05-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='收费项目描述'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='project',
            field=models.ForeignKey(blank=True, help_text='必选：6个合作项目之一，系统自动按项目汇总每月收入', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='projects.project', verbose_name='归属项目'),
        ),
    ]
