# Generated by Django 6.0.5 on 2026-05-11 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=200, verbose_name='中文名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('category', models.CharField(default='保健品', max_length=50, verbose_name='类别')),
                ('unit', models.CharField(default='瓶', help_text='如：瓶、盒、粒', max_length=20, verbose_name='最小单位')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='成本单价')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='默认等于成本价', max_digits=12, verbose_name='销售单价')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应商/采购平台')),
                ('current_stock', models.IntegerField(default=0, verbose_name='当前库存数量')),
                ('min_stock_threshold', models.IntegerField(default=10, verbose_name='库存预警阈值')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='批次号')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='条形码')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'inventory_product',
                'ordering': ['name_cn'],
                'indexes': [models.Index(fields=['name_cn'], name='inventory_p_name_cn_ea09d6_idx'), models.Index(fields=['supplier'], name='inventory_p_supplie_ee595d_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.IntegerField(verbose_name='入库数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='总金额')),
                ('type', models.CharField(choices=[('purchase', '采购入库'), ('return', '退货入库'), ('adjust', '盘点调整')], default='purchase', max_length=20, verbose_name='入库类型')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应商')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='批次号')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('confirmed', models.BooleanField(default=False, verbose_name='已确认')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='inventory.product', verbose_name='商品')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '入库记录',
                'verbose_name_plural': '入库记录',
                'db_table': 'inventory_stock_in',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.IntegerField(verbose_name='出库数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='总金额')),
                ('out_type', models.CharField(choices=[('sale', '销售出库'), ('scrap', '报废出库')], default='sale', max_length=20, verbose_name='出库类型')),
                ('customer_name', models.CharField(blank=True, help_text='关联VIP会员', max_length=100, verbose_name='客户姓名')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='出库时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='inventory.product', verbose_name='商品')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '出库记录',
                'verbose_name_plural': '出库记录',
                'db_table': 'inventory_stock_out',
                'ordering': ['-created_at'],
            },
        ),
    ]
