# Generated by Django 6.0.5 on 2026-05-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='vip_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_outs', to='vip.vipmember', verbose_name='关联会员'),
        ),
    ]
