# Generated by Django 6.0.5 on 2026-05-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockout',
            name='vip_member',
        ),
        migrations.AddField(
            model_name='stockout',
            name='cost_category',
            field=models.ForeignKey(blank=True, help_text='根据物品类别自动映射：打针类→打针，补剂类→补剂', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='projects.costcategory', verbose_name='费用科目'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='projects.project', verbose_name='归属项目'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('injection', '打针类'), ('supplement', '补剂类'), ('other', '其他')], default='supplement', max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='默认 = 成本价 × 130%', max_digits=12, verbose_name='销售单价'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='customer_name',
            field=models.CharField(help_text='必填', max_length=100, verbose_name='客户姓名'),
        ),
    ]
