# Generated by Django 6.0.5 on 2026-05-11 08:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('lab_bills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=10, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='电话')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='证件号')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'VIP会员',
                'verbose_name_plural': 'VIP会员',
                'db_table': 'vip_member',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VIPCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.IntegerField(choices=[(3, '3个月'), (6, '6个月'), (12, '12个月')], verbose_name='疗程时长(月)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='范围: 30,000 - 250,000', max_digits=12, verbose_name='疗程总价')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('attending_doctor', models.CharField(blank=True, max_length=100, verbose_name='合作医生')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('paused', '已暂停')], default='active', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='vip.vipmember', verbose_name='会员')),
            ],
            options={
                'verbose_name': '疗程',
                'verbose_name_plural': '疗程',
                'db_table': 'vip_course',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VIPCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cost_type', models.CharField(choices=[('first_visit', '首次门诊+血检'), ('injection', '点滴注射'), ('supplements', '餐包及营养补给'), ('blood_test', '血检'), ('imaging', '影像'), ('nurse_labor', '护士人工'), ('reception', '客户接待'), ('fixed_cost', '固定费用'), ('other', '其他自定义')], db_index=True, max_length=20, verbose_name='费用类型')),
                ('custom_name', models.CharField(blank=True, help_text='仅"其他自定义"类型使用', max_length=100, verbose_name='自定义名称')),
                ('standard_amount', models.DecimalField(decimal_places=2, default=0, help_text='标准/参考金额', max_digits=12, verbose_name='标准金额')),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, help_text='实际成本金额', max_digits=12, verbose_name='成本金额')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='此项费用总金额', max_digits=12, verbose_name='总金额')),
                ('is_per_course', models.BooleanField(default=False, help_text='固定费用类：总金额均分到每个疗程', verbose_name='按疗程均摊')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('cost_date', models.DateField(blank=True, null=True, verbose_name='费用日期')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('lab_bill_records', models.ManyToManyField(blank=True, to='lab_bills.labbillrecord', verbose_name='关联血检/影像账单')),
                ('stock_out_records', models.ManyToManyField(blank=True, to='inventory.stockout', verbose_name='关联保健品出库')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='vip.vipcourse', verbose_name='关联疗程')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='vip.vipmember', verbose_name='会员')),
            ],
            options={
                'verbose_name': '疗程费用项',
                'verbose_name_plural': '疗程费用项',
                'db_table': 'vip_cost_item',
                'ordering': ['member', 'course', 'cost_type'],
            },
        ),
        migrations.CreateModel(
            name='VIPPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='收款金额')),
                ('payment_date', models.DateField(db_index=True, verbose_name='收款日期')),
                ('project_type', models.CharField(help_text='如: 首次门诊、疗程费用、药费等', max_length=100, verbose_name='项目类型')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='vip.vipcourse', verbose_name='关联疗程')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vip.vipmember', verbose_name='会员')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '收款记录',
                'verbose_name_plural': '收款记录',
                'db_table': 'vip_payment',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='VIPRevenueRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('revenue_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='确认收入')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='已确认')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.vipcourse', verbose_name='疗程')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.vipmember', verbose_name='会员')),
            ],
            options={
                'verbose_name': '收入确认',
                'verbose_name_plural': '收入确认',
                'db_table': 'vip_revenue_recognition',
                'ordering': ['year', 'month', 'member'],
                'unique_together': {('course', 'year', 'month')},
            },
        ),
    ]
