# Generated by Django 6.0.5 on 2026-05-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenuePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='合作方名称')),
                ('project', models.CharField(choices=[('anti_aging', '抗衰老'), ('lifestyle', '生活方式门诊'), ('hormone', '荷尔蒙')], max_length=50, verbose_name='关联项目')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '分成合作方',
                'verbose_name_plural': '分成合作方',
                'db_table': 'revenue_share_partner',
            },
        ),
        migrations.CreateModel(
            name='RevenueShareCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('total_course_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='疗程总收入')),
                ('nurse_reception_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='扣除护士/接待费')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总扣除额')),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='净收入(分成前)')),
                ('partner_share', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='应付分成')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('settled', '已结算')], default='draft', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='计算时间')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='revenue_share.revenuepartner', verbose_name='合作方')),
            ],
            options={
                'verbose_name': '分成计算',
                'verbose_name_plural': '分成计算',
                'db_table': 'revenue_share_calculation',
                'ordering': ['-year', '-month', 'partner'],
                'unique_together': {('partner', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='RevenueShareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_rate', models.DecimalField(decimal_places=4, default=0.1, help_text='如 0.10 表示扣除10%', max_digits=5, verbose_name='护士/接待费扣除比例')),
                ('partner_share_ratio', models.DecimalField(decimal_places=4, default=0.5, help_text='如 0.50 表示50%', max_digits=5, verbose_name='合作方分成比例')),
                ('deduct_lab_bills', models.BooleanField(default=True, verbose_name='扣除实验室费用')),
                ('deduct_supplements', models.BooleanField(default=True, verbose_name='扣除保健品费用')),
                ('deduct_imaging', models.BooleanField(default=True, verbose_name='扣除影像费用')),
                ('deduct_nurse', models.BooleanField(default=True, verbose_name='扣除护士人工')),
                ('deduct_reception', models.BooleanField(default=True, verbose_name='扣除客户接待')),
                ('deduct_travel', models.BooleanField(default=True, verbose_name='扣除差旅费')),
                ('deduct_fixed', models.BooleanField(default=True, verbose_name='扣除固定费用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_config', to='revenue_share.revenuepartner', verbose_name='合作方')),
            ],
            options={
                'verbose_name': '分成配置',
                'verbose_name_plural': '分成配置',
                'db_table': 'revenue_share_config',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('statement_data', models.JSONField(blank=True, default=dict, verbose_name='对账明细')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='对账总金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('sent', '已发送'), ('confirmed', '已确认')], default='draft', max_length=20, verbose_name='状态')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue_share.revenuepartner', verbose_name='合作方')),
                ('calculation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue_share.revenuesharecalculation', verbose_name='关联分成计算')),
            ],
            options={
                'verbose_name': '对账单',
                'verbose_name_plural': '对账单',
                'db_table': 'revenue_share_statement',
                'ordering': ['-year', '-month'],
                'unique_together': {('partner', 'year', 'month')},
            },
        ),
    ]
