# Generated by Django 6.0.5 on 2026-05-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_editable', models.BooleanField(default=False, help_text='运动康复、神经康复等简单模块支持在线编辑', verbose_name='可在线编辑')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '报表分类',
                'verbose_name_plural': '报表分类',
                'db_table': 'reports_category',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='单价')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.reportcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '报表项目',
                'verbose_name_plural': '报表项目',
                'db_table': 'reports_item',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='金额')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('report_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_entries', to='reports.reportitem', verbose_name='报表项目')),
            ],
            options={
                'verbose_name': '月度报表数据',
                'verbose_name_plural': '月度报表数据',
                'db_table': 'reports_entry',
                'ordering': ['-year', '-month', 'report_item'],
                'unique_together': {('report_item', 'year', 'month')},
            },
        ),
    ]
